-- Create table for vehicle reviews
-- This table stores customer reviews and ratings for inventory items

CREATE TABLE IF NOT EXISTS public.review (
    review_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_id INTEGER NOT NULL,
    account_id INTEGER NOT NULL,
    review_text TEXT NOT NULL,
    review_rating INTEGER NOT NULL,
    review_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT review_pkey PRIMARY KEY (review_id),
    CONSTRAINT review_rating_check CHECK (review_rating >= 1 AND review_rating <= 5),
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id) 
        REFERENCES public.inventory (inv_id) 
        MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_account FOREIGN KEY (account_id) 
        REFERENCES public.account (account_id) 
        MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
);

-- Create index for faster queries on inventory items
CREATE INDEX idx_review_inv_id ON public.review(inv_id);

-- Create index for faster queries on account reviews
CREATE INDEX idx_review_account_id ON public.review(account_id);

-- Sample comment for testing (optional - uncomment if you have test data)
-- INSERT INTO public.review (inv_id, account_id, review_text, review_rating)
-- VALUES (1, 1, 'Great car! Very satisfied with the performance and handling.', 5);
